Hooks:PostHook(MoneyTweakData, "init", "CrimDawn_MoneyTweakInit", function(self, tweak_data)
  self.weapon_cost = 0
  self.modify_weapon_cost = 0
  self.modify_weapon_cost = 0
  self.masks = {
    mask_value = 0,
    material_value = 0,
    pattern_value = 0,
    color_value = 0
  }
  self.mission_asset_cost_small = self._create_value_table(10000, 25000, 10, true, 1)
  self.mission_asset_cost_medium = self._create_value_table(20000, 75000, 10, true, 1)
  self.mission_asset_cost_large = self._create_value_table(100000, 500000, 10, true, 1)

  self.mission_asset_cost_multiplier_by_risk = { 1, 2, 5, 10, 13, 13, 13 }

  self.preplaning_asset_cost_thermite = 50000
  self.preplaning_asset_cost_escapebig = 25000
	self.preplaning_asset_cost_spycam = 5000
	self.preplaning_asset_cost_delay10 = 10000
	self.preplaning_asset_cost_delay20 = 20000
	self.preplaning_asset_cost_delay30 = 30000
	self.preplaning_asset_cost_timelock60 = 30000
	self.preplaning_asset_cost_cake = 5000
	self.preplaning_asset_cost_extracameras = 1000
	self.preplaning_asset_cost_accesscameras = 2000
	self.preplaning_asset_cost_drillparts = 10000
	self.preplaning_asset_cost_deaddropbag = 15000
	self.preplaning_asset_cost_unlocked_door = 5000
	self.preplaning_asset_cost_unlocked_window = 5000
	self.preplaning_asset_cost_zipline = 10000
	self.preplaning_asset_cost_highlight_keybox = 5000
	self.preplaning_asset_cost_keycard = 7500
	self.preplaning_asset_cost_disable_alarm_button = 5000
	self.preplaning_asset_cost_safe_escape = 40000
	self.preplaning_asset_cost_sniper_spot = 10000
	self.preplaning_asset_cost_framing_frame_1_truck = 5000
	self.preplaning_asset_cost_framing_frame_1_entry_point = 5000
	self.preplaning_asset_cost_bag_shortcut = 5000
	self.preplaning_asset_cost_bag_zipline = 10000
	self.preplaning_asset_cost_loot_drop_off = 10000
	self.preplaning_asset_cost_thermal_paste = 5000
	self.preplaning_asset_cost_branchbank_vault_key = 20000
	self.preplaning_mia_cost_sniper = 15000
	self.preplaning_mia_cost_delayed_police = 30000
	self.preplaning_mia_cost_reduce_mobsters = 10000
	self.preplaning_asset_cost_glass_cutter = 2000
	self.preplaning_thebomb_cost_spotter = 5000
	self.preplaning_thebomb_cost_crowbar = 2000
	self.preplaning_thebomb_cost_ladder = 1000
	self.preplaning_thebomb_cost_hacker = 10000
	self.preplaning_thebomb_cost_manifest = 2500
	self.preplaning_thebomb_cost_pilot = 10000
	self.preplaning_thebomb_cost_escape_mid = 20000
	self.preplaning_thebomb_cost_escape_close = 40000
	self.preplaning_thebomb_cost_demolition = 5000
	self.preplaning_asset_cost_roof_access = 10000
	self.preplaning_asset_cost_upper_floor_access = 10000
	self.preplaning_asset_cost_crowbar_single = 2000
	self.preplaning_asset_cost_mex_keys = 2000
	self.preplanning_asset_cost_bex_car_pull = 10000
	self.preplanning_asset_cost_bex_drunk_mariachi = 5000
	self.preplanning_asset_cost_bex_garbage_truck = 5000
	self.preplanning_asset_cost_bex_zipline = 8000
	self.preplanning_asset_cost_pex_parked_car = 2000
	self.preplanning_asset_cost_pex_spiked_churro = 2000
	self.preplanning_asset_cost_pex_camera_access = 2000
	self.preplanning_asset_cost_pex_open_window = 2000
	self.preplanning_asset_cost_fex_stealth_entry_with_boat = 2000
	self.preplanning_asset_cost_fex_loud_escape_with_heli = 2000
	self.preplanning_asset_cost_fex_stealth_semi_open_garage_door = 2000
	self.preplanning_asset_cost_kenaz_zeppelin_escape = 25000
	self.preplanning_asset_cost_kenaz_van_escape = 30000
	self.preplanning_asset_cost_kenaz_loud_entry_with_c4 = 5000
	self.preplanning_asset_cost_kenaz_drill_better_plasma_cutter = 5000
	self.preplanning_asset_cost_kenaz_drill_improved_cooling_system = 5000
	self.preplanning_asset_cost_kenaz_drill_engine_optimization = 10000
	self.preplanning_asset_cost_kenaz_drill_engine_additional_power = 20000
	self.preplanning_asset_cost_kenaz_drill_extra_battery = 10000
	self.preplanning_asset_cost_kenaz_drill_water_level_indicator = 0
	self.preplanning_asset_cost_kenaz_drill_timer_addon = 0
	self.preplanning_asset_cost_kenaz_drill_toolbox = 5000
	self.preplanning_asset_cost_kenaz_drill_medkit = 15000
	self.preplanning_asset_cost_kenaz_drill_ammobox = 15000
	self.preplanning_asset_cost_kenaz_ace_pilot = 5000
	self.preplanning_asset_cost_kenaz_faster_blimp = 5000
	self.preplanning_asset_cost_kenaz_sabotage_skylight_barrier = 5000
	self.preplanning_asset_cost_kenaz_unlocked_cages = 10000
	self.preplanning_asset_cost_kenaz_unlocked_doors = 5000
	self.preplanning_asset_cost_kenaz_guitar_case_position = 0
	self.preplanning_asset_cost_kenaz_disable_metal_detectors = 0
	self.preplanning_asset_cost_kenaz_celebrity_visit = 5000
	self.preplanning_asset_cost_kenaz_vault_gate_key = 5000
	self.preplanning_asset_cost_chas_tram = 10000
end)